In [5]:
# Import API key
# This will be my Weather API 
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests 
import random
import time
from scipy.stats import linregress

# Import API key
from config import api_key_OpenWeather, api_key_Google

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

ModuleNotFoundError: No module named 'config'

In [6]:
# Create Dataframe with the Columns needed, then populate Lat and Lng columns
location_data = pd.DataFrame(columns =['Lat', 'Lng', 'City', 'Country', 'Temperature', 
                                       'Humidity', 'Clouds', 'Windspeed', 'Latitude', 'Longitude'])
lat = []
lng = []
for x in range(1, 1500):
    lat.append(random.uniform(-90, 90)) 
    lng.append(random.uniform (-180, 180))
location_data['Lat'] = lat
location_data['Lng'] = lng
location_data

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude
0,-20.491260,-82.930781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50.315872,-55.190796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,66.067524,56.539918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-69.133031,142.447335,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,70.264160,130.694917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,33.870581,-49.830065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,43.204684,-76.473432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,73.802908,-97.364631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,76.150940,-78.753613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,-51.728654,-28.107046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,-18.260733,118.384395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,89.584259,42.187088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,35.980314,21.862562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,-80.565472,160.249137,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,-14.918748,179.103885,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,69.423797,144.453469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,-39.128976,-59.610591,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,-41.109441,155.347177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,75.778393,-174.860155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,7.824183,106.667277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,89.785980,-18.499952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,48.745069,-110.309807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,-22.123378,86.950964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,-29.636635,-2.329608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,37.846988,81.335900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,52.543522,-176.796746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,87.118050,72.852333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,63.273416,81.725934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,-56.930871,82.676963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,12.288239,38.750138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1469,-54.232008,-43.176567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1470,30.397006,71.842341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1471,-32.529259,-32.485397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1472,59.554503,32.103504,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1473,-1.028951,46.230179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1474,-0.585026,-1.507818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1475,-15.992155,-127.475875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1476,-5.881914,109.658611,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,-80.574084,175.565439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1478,8.564880,168.103377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1479,-1.094847,3.503089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,16.925702,18.266678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,14.115754,-65.240949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1482,37.801451,-6.680710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,34.295028,148.168586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,16.943356,-109.001278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1485,72.168155,-0.967089,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1486,21.944870,130.996356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1487,-86.747824,11.005015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1488,-66.325168,75.658862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1489,-77.977988,29.216176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1490,33.687954,132.180524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1491,-20.413829,-93.847794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1492,-17.740556,121.385279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1493,-42.696048,63.289100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1494,19.662676,26.682276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1495,-74.641792,-67.917549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1496,2.315508,-153.151722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1497,72.691585,-157.142855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1498,51.873651,-91.493276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Find City and Country from citipy based on Lat and Lng data and populate data frame
Cities = []
Country = []
for index, row in location_data.iterrows():
    city=citipy.nearest_city(row['Lat'], row['Lng'])
    country=citipy.nearest_city(row['Lat'], row['Lng'])
    Cities.append(city.city_name)
    Country.append(country.country_code)
location_data['City']=Cities
location_data['Country']=Country
location_data.head()

NameError: name 'citipy' is not defined

In [8]:
# Make sure the datset has no duplicate values
location_data = location_data.drop_duplicates(['City', 'Country'])
len(location_data['City'].value_counts())

0

In [9]:
# Review Data
location_data

,Lat,Lng,City,Country,Temperature,Humidity,Clouds,Windspeed,Latitude,Longitude
0,-20.49126,-82.930781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN